# Generated by Django 5.1.3 on 2025-05-21 10:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='unsubscribe_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
