# Generated by Django 5.1.3 on 2025-05-21 10:25

import uuid
from django.db import migrations


def gen_uuid(apps, schema_editor):
    NewsletterSubscriber = apps.get_model('newsletter', 'NewsletterSubscriber')
    for subscriber in NewsletterSubscriber.objects.all():
        subscriber.unsubscribe_token = uuid.uuid4()
        subscriber.save(update_fields=['unsubscribe_token'])

class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_newslettersubscriber_unsubscribe_token'),
    ]

    operations = [
        migrations.RunPython(gen_uuid),
    ]
