# Generated by Django 5.1.3 on 2025-06-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products/dgdefault.png', null=True, upload_to='products/'),
        ),
    ]
